version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: nidos-transcribe:latest
    container_name: nidos-transcribe
    ports:
      - "8000:8000"
    env_file:
      - .env
    # Mount local store so models and speaker_db.json persist and are NOT baked into the image
    volumes:
      - ./app/store:/app/app/store
      # Mount the simple web UI for live editing/reload in the container
      - ./web:/app/web
    # Optional GPU (uncomment if you have NVIDIA toolkit set up)
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    device_requests:
      - driver: nvidia
        count: all
        capabilities: [gpu]
