version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: nidos-transcribe:latest
    container_name: nidos-transcribe
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app/store:/app/app/store
      - ./web:/app/web
    # Enable GPU (optional). Requires Docker Desktop + NVIDIA toolkit.
    # gpus: all
